Versie 1: carrousel beschikbare stekjes  🍃
fdnd-agency/buurtcampus-oost pull request #21
Opened 2024-03-04 17:38 UTC by Nazneen05x

Ik ben afgelopen week bezig geweest met het bouwen van de carrousel voor de beschikbare stekjes. 

## Done ✅

Ik ben eerst begonnen met het opzetten van de html structuur en daarna gestijld met css. De carrousel werkt op dit moment alleen door te scrollen.

- [x] Pijltjes
- [x] scroll overflow (display/flex)
- [x] scroll-snap
- [x] Styling (css) (desktop)
- [x]  scroll-driven-animation
- [x]  Html structuur
- [x] img lazy: loading
- [x] Content uit data

## To do  ❌⁉️

- [ ] Pijltjes laten werken
- [ ] Indicators toevoegen en laten werken
- [ ] Responsive maken (mobile & tablet)
- [ ] Styling  (css) (mobile & tablet)

Extra

- Testen (lighthouse)

<img width="700" alt="Scherm­afbeelding 2024-03-04 om 18 34 37" src="https://github.com/fdnd-agency/buurtcampus-oost/assets/112861261/589eb7ac-b9a8-4eb0-bf39-67dece1dc343">

2024-03-05 10:18 UTC, joostf commented
@Nazneen05x  It might be better to hide the arrows until they are enabled with javascript?!

2024-03-05 15:14 UTC, Nazneen05x commented
Hi @joostf good idea! I'll put it on my carrousel to do list 😊. 
To be sure, you mean when JavaScript doesn't work, the arrows are not visible?😊

2024-03-13 14:42 UTC, joostf requested changes
Qua responsive gaat het nog niet overal helemaal goed:

Het plaatje schaalt alleen horizontaal:
<img width="1239" alt="image" src="https://github.com/fdnd-agency/buurtcampus-oost/assets/1061632/1d1397b0-c076-4caf-a462-daa94724fd5a">

De varens in de footer mog ook wat meeschaslen denk ik:
<img width="1110" alt="image" src="https://github.com/fdnd-agency/buurtcampus-oost/assets/1061632/5844578f-ed97-4f2e-a5c2-836b30cb4e1a">

2024-03-13 14:42 UTC, joostf commented on src/lib/atoms/carousel/Carouselstekje.svelte
>  <div class="carousel-container">
Waarom is dit een div element? Kan je hiervoor een semantisch element gebruiken?

2024-03-13 14:42 UTC, joostf commented on src/lib/atoms/carousel/Carouselstekje.svelte
>  <div class="carousel-container">
Klopt het dat er onder de caroussel veel witruimte zit?

<img width="1524" alt="image" src="https://github.com/fdnd-agency/buurtcampus-oost/assets/1061632/6049b6fd-6a57-429b-936e-80ab4f35372d">

2024-03-13 14:42 UTC, joostf commented on src/lib/atoms/sections/SectionFourHome.svelte
> +  import Carouselstekje from "../carousel/Carouselstekje.svelte";
Probeer consistenter te zijn qua naamgeving, gebruik alleen engels hiervoor

2024-04-19 09:47 UTC, joostf commented
@Nazneen05x ik zie dat er .env bestanden gepushed zijn naar live met keys erin. Graag deze bestanden verwijderen van de origin!

2024-04-23 08:19 UTC, merged