Navbar werkt responsive :rocket:
fdnd-agency/buurtcampus-oost pull request #46
Opened 2024-05-06 09:53 UTC by JalalToufik

Heb de navbar geupdate met nieuwe linkjes en de style toegepast, liep een beetje vast met de Onmount code in de Navbar-code. Hier heb ik even een ignore gezet voor nu.

2024-05-07 09:15 UTC, ju5tu5 requested changes
Hi @JalalToufik, nog een paar aanpassingen, belangrijkste dingen zijn: 
- SVG's even door SVGOMG heen trekken, gewoon met de standaard opties aangevinkt. Dit optimaliseert SVG's voor gebruik op het web. Alle SVG's van tabler hebben een soort watermerk path (de bovenste) die je gewoon weg kunt halen. Scheelt weer een paar kB's.
- Semantische HTML elementen in je carroussel, <div>'s zijn niet echt beschrijvend voor wat er binnen in gebeurt. Hint: Een carroussel is een soort lijst met afbeeldingen.

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/atoms/icons/cross copy.svelte
Kan de naamgeving beter? Moet het woord 'copy' in de naam?

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/atoms/icons/hamburger copy.svelte
Kan de naamgeving beter? Moet het woord 'copy' in de naam?

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/atoms/icons/cross copy.svelte
Also, haal het even door SVGOMG heen en verwijder onnodige attributen, de class en volgens mij de bovenste path zijn overbodig.

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/atoms/icons/hamburger copy.svelte
Also, haal het even door SVGOMG heen en verwijder onnodige attributen, de class en volgens mij de bovenste path zijn overbodig.

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/atoms/logo/plantswaplogo.svelte
Haal het even door SVGOMG heen.

2024-05-07 09:15 UTC, ju5tu5 commented on src/lib/molecules/Carousel.svelte
De carroussel is een verzameling <div>'s, kan je semantischer elementen toepassen?

2024-05-08 07:47 UTC, JalalToufik commented on src/lib/atoms/logo/plantswaplogo.svelte
Yes heb er een issue van gemaakt, zal dit gelijk oppakken!

2024-05-08 07:51 UTC, JalalToufik commented on src/lib/molecules/Carousel.svelte
Ik zal hier naar kijken, maak ook hier een issue van!

2024-05-09 09:00 UTC, ju5tu5 commented
Mooi! Ik ga mergen...

2024-05-09 09:01 UTC, merged